---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/4/30 15:18
---

require("LuaConf/RequireLuaFiles")

local BagMain = class("BagMain")


function awake()
    print("lua awake...")
    BagMain.New()
end

function BagMain:Ctor()
    
end


return BagMain
