---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/4/26 16:14
---

local BagWindow =fgui.window_class() -- class("BagWindow", fgui.window_class) 需要继承C#的类


function BagWindow:Ctor()  -- 同cdx不同，直接覆盖即可,注意函数名
end

function BagWindow:OnInit()
    self.contentPane = fgui.UIPackage.CreateObject("Bag", "BagWin").asCom
    self:Center()
    self.modal = true
    _list = self.contentPane:GetChild("list").asList
    _list.onClickItem:Add(function(context)
        item = context.data
        self.contentPane:GetChild("n11").asLoader.url = item.icon;
        self.contentPane:GetChild("n13").text = item.icon;
    end)
    _list.itemRenderer = function(index, obj)
        obj.icon = "i" .. math.random(0,10)
        obj.title = "" .. math.random(0,100)
    end
    _list.numItems = 45
    -- self:center()
end

function BagWindow:__clickItem(context)
    item = context.data
    self.contentPane:GetChild("n11").asLoader.url = item.icon;
    self.contentPane:GetChild("n13").text = item.icon;
end

function BagWindow:RenderListItem(index, obj)
    obj.icon = "i" + math.random(0,10)
    obj.title = "" + math.random(0,100)
end

function BagWindow:DoShowAnimation() 
    self:SetScale(0.1,0.1)
    self:SetPivot(0.5,0.5)
    self:TweenScale(CS.UnityEngine.Vector2(1,1), 0.3):OnComplete(function()  end)
end

function BagWindow:DoHideAnimation()
    self:TweenScale(CS.UnityEngine.Vector2(0.1,0.1), 0.3):OnComplete(xutil.bind(self.HideImmediately, self))
end

return BagWindow