---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/5/7 16:19
---

require("LuaConf/RequireLuaFiles")
local CooldownMain = class("CooldownMain")
data = nil
function awake()
    print("lua awake...")
    data = CooldownMain.New()
end

function CooldownMain:Ctor()
    fgui.UIPackage.AddPackage("UI/Cooldown")
    CS.UnityEngine.Application.targetFrameRate = 60
    fgui.Stage.inst.onKeyDown:Add(xutil.bind(self.OnKeyDown, self))
    --self._mainView = this.gameObject:GetComponent(typeof(CS.FairyGUI.UIPanel)).ui
    self._mainView = UIPackage.CreateObject("Cooldown", "Main")  -- 这两行同 this:GetComponent(typeof(CS.FairyGUI.UIPanel)).ui
    GRoot.inst:AddChild(self._mainView)
    self._btn0 = self._mainView:GetChild("b0").asButton;
    self._btn0.icon = "Cooldown/k0";
    self._time1 = 5
    self._mask0 = self._btn0:GetChild("mask").asImage

    self._btn1 = self._mainView:GetChild("b1").asButton
    self._btn1.icon = "Cooldown/k1"
    self._time2 = 10
    self._mask1 = self._btn1:GetChild("mask").asImage
end

function CooldownMain:OnKeyDown(context)
    if context.inputEvent.keyCode == CS.UnityEngine.KeyCode.Escape then
        CS.UnityEngine.Application.Quit();
    end
end

function update()
    data:Update()
end

function CooldownMain:Update()
    self._time1 = self._time1 - CS.UnityEngine.Time.deltaTime
    if self._time1 < 0 then
        self._time1 = 5
    end
    self._mask0.fillAmount = 1 - (5 - self._time1) / 5;

    self._time2 = self._time2 - CS.UnityEngine.Time.deltaTime;
    if self._time2 < 0 then
        self._time2 = 10
    end
    self._btn1.text = CS.System.String.Empty .. CS.UnityEngine.Mathf.RoundToInt(self._time2);
    self._mask1.fillAmount = 1 - (10 - self._time2) / 10;
    
end
    
return CooldownMain