---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/5/7 16:51
---

require("LuaConf/RequireLuaFiles")
local CurveMain = class("CurveMain")

function awake()
    print("lua awake...")
    CurveMain.New()
end

function CurveMain:Ctor()
    CS.UnityEngine.Application.targetFrameRate = 60
    fgui.Stage.inst.onKeyDown:Add(xutil.bind(self.OnKeyDown, self))
    self._mainView = this.gameObject:GetComponent(typeof(CS.FairyGUI.UIPanel)).ui
    self._list = self._mainView:GetChild("list").asList;
    self._list:SetVirtualAndLoop()
    self._list.itemRenderer = xutil.bind(self.RenderListItem, self)
    self._list.numItems = 5;
    self._list.scrollPane.onScroll:Add(xutil.bind(self.DoSpecialEffect, self));
    
    self:DoSpecialEffect()
    
end

function CurveMain:OnKeyDown(context)
    if context.inputEvent.keyCode == CS.UnityEngine.KeyCode.Escape then
        CS.UnityEngine.Application.Quit();
    end
end

function CurveMain:RenderListItem(index, obj)
    obj:SetPivot(0.5, 0.5)
    obj.icon = fgui.UIPackage.GetItemURL("Curve", "n" .. (index + 1));
end

function CurveMain:DoSpecialEffect()
    local midx = self._list.scrollPane.posX + self._list.viewWidth / 2
    local cnt = self._list.numChildren
    for i = 1, cnt-1 do
        local obj = self._list:GetChildAt(i)
        local dist = math.abs(midx - obj.x - obj.width /2)
        if dist > obj.width then
            obj:SetScale(1, 1)
        else
            local ss = 1 + (1 - dist / obj.width) * 0.24
            obj:SetScale(ss, ss)
        end
    end
    
end



