---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/5/7 17:41
---  TODO 功能待确认！

require("LuaConf/RequireLuaFiles")
local CutSceneMain = class("CutSceneMain")

function awake()
    print("lua awake...")
    CutSceneMain.New()
end

function CutSceneMain:Ctor()
    CS.UnityEngine.Application.targetFrameRate = 60
    fgui.Stage.inst.onKeyDown:Add(xutil.bind(self.OnKeyDown, self))
    fgui.UIPackage.AddPackage("UI/CutScene")
    
    self._cutSceneView = fgui.UIPackage.CreateObject("CutScene", "CutScene").asCom
    self._cutSceneView:SetSize(GRoot.inst.width, GRoot.inst.height)
    self._cutSceneView:AddRelation(GRoot.inst, CS.FairyGUI.RelationType.Size)
    
    self._mainView = UIPackage.CreateObject("CutScene", "Main").asCom
    self._mainView:SetSize(GRoot.inst.width, GRoot.inst.height)
    self._mainView:AddRelation(GRoot.inst, CS.FairyGUI.RelationType.Size);
    print_r(self._mainView:GetChild("n0"))
    self._mainView:GetChild("n0").onClick:Add(function()
        self:LoadLevel("scene1")
    end)

    self._mainView:GetChild("n1").onClick:Add(function()
        self:LoadLevel("scene2")
    end)
    
end

function CutSceneMain:OnKeyDown(context)
    if context.inputEvent.keyCode == CS.UnityEngine.KeyCode.Escape then
        CS.UnityEngine.Application.Quit();
    end
end


function CutSceneMain:LoadLevel(levelName)
    CS.UnityEngine.StartCoroutine(self:DoLoad(levelName))
    GRoot.inst:AddChild(self._cutSceneView)
end

function CutSceneMain:DoLoad(sceneName)
    print(sceneName, type(sceneName))
    GRoot.inst:AddChild(self._cutSceneView)
    local pb = self._cutSceneView:GetChild("pb").asProgress
    pb.value = 0
    local op = CS.UnityEngine.SceneManagement.SceneManager.LoadSceneAsync(sceneName)
    local startTime = CS.UnityEngine.Time.time
    while ~op.isDone or pb.value ~= 100 do
        local value = (CS.UnityEngine.Time.time - startTime) * 100 / 3
        if value > 100 then
            value = 100
        end
        pb.value = value
        coroutine.yield(function() return nil end)  
    end

    GRoot.inst:RemoveChild(self._cutSceneView);
    GRoot.inst:AddChild(self._mainView);
end


