---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/5/26 16:50
---

require("LuaConf/RequireLuaFiles")

local Games = class("Games")

function Games:Ctor()
    --local Prefab = CS.UnityEditor.AssetDatabase.LoadAssetAtPath("Assets/Resources/Spine/Player.prefab")  -- TODO 在C#处加载该方法
    --local obj = CS.UnityEngine.GameObject.Find("GameObject")
    --CS.UnityEngine.Object.Instantiate(Prefab, CS.UnityEngine.Vector3(-5.9, 0.8, 0), CS.UnityEngine.Quaternion.Euler(0,0,0),obj.transform).name = "player"
    --CS.UnityEngine.Instantiate(Prefab, CS.UnityEngine.Vector3(5.39, -2.47, 0), CS.UnityEngine.Quaternion.Euler(0, 180, 0), obj.transform).name = "monster"
    self.o = CS.UnityEngine.GameObject.Find("monster")
    self.player = CS.UnityEngine.GameObject.Find("player")
end

function Games:Update()
    local dist = CS.UnityEngine.Vector3.Distance(self.player.transform.position, self.o.transform.position)
    if dist < 3.0 then
        local player = self.player:GetComponent(typeof(CS.Spine.Unity.SkeletonAnimation))
        local a = self.o:GetComponent(typeof(CS.Spine.Unity.SkeletonAnimation))
        player.AnimationName = "Attack"
        a.AnimationName = "Attack"
    else
        local play = self.player.transform.position;
        local monster = self.o.transform.position;
        self.player.transform.position = CS.UnityEngine.Vector3.MoveTowards(play, monster, 1 * CS.UnityEngine.Time.deltaTime);
        self.o.transform.position = CS.UnityEngine.Vector3.MoveTowards(monster, play, 1 * CS.UnityEngine.Time.deltaTime);
        local player = self.player:GetComponent(typeof(CS.Spine.Unity.SkeletonAnimation));
        player.AnimationName = "Move";
        player.loop = true;

        local a = self.o:GetComponent(typeof(CS.Spine.Unity.SkeletonAnimation));
        a.AnimationName = "Move";
        a.loop = true;
    end
end

return Games