---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/5/18 17:05
---

require("LuaConf/RequireLuaFiles")
local Guide = class("Guide")


function awake()
    print("lua awake...")
    Guide.New()
end


function Guide:Ctor()
    fgui.UIPackage.AddPackage("UI/Guide")
    local view = fgui.UIPackage.CreateObject("Guide", "Main")
    GRoot.inst:AddChild(view)
    local guideLayer = fgui.UIPackage.CreateObject("Guide", "GuideLayer")
    guideLayer:SetSize(GRoot.inst.width, GRoot.inst.height)
    guideLayer:AddRelation(GRoot.inst, CS.FairyGUI.RelationType.Size)
    local bagBtn = view:GetChild("bagBtn")
    bagBtn.onClick:Add(function()
        print(type(guideLayer))
        guideLayer:Dispose()
        --CS.UnityEngine.Object.Destroy(guideLayer)
        --guideLayer:RemoveFromParent()
    end)
    view:GetChild("n2").onClick:Add(function()
        if guideLayer.isDisposed then
            guideLayer = fgui.UIPackage.CreateObject("Guide", "GuideLayer")
        end
        GRoot.inst:AddChild(guideLayer)
        local rect = bagBtn:TransformRect(CS.UnityEngine.Rect(0, 0, bagBtn.width, bagBtn.height), guideLayer)
        local window = guideLayer:GetChild("window")
        window.size = CS.UnityEngine.Vector2(rect.size.x, rect.size.y)
        window:TweenMove(CS.UnityEngine.Vector2(rect.position.x, rect.position.y), 0.5)
    end)
end

return Guide
