---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/5/8 9:56
--- 
-- TODO 关于UI切换，可用UI状态机 http://jxwgame.blog.51cto.com/943299/1613585 

require("LuaConf.RequireLuaFiles")

local MenuScene = class("MenuScene")


function awake()
    print("lua awake...")
    MenuScene.New()
end

function MenuScene:Ctor()
    self.groot = GRoot.inst
    fgui.UIPackage.AddPackage("UI/MainMenu")
    local view = fgui.UIPackage.CreateObject("MainMenu", "Main")
    self.groot:AddChild(view)
    local cnt = view.numChildren
    for i = 1, cnt do
        local obj = view:GetChildAt(i-1)
        if obj.name ~= "n3" then
            obj.onClick:Add(handler(self, self.runDemo))
        end
    end
end


function MenuScene:runDemo(context, a)
    print("context:getSender:", context.sender.name)
    local name = context.sender.name
    
    CS.UnityEngine.SceneManagement.SceneManager.LoadScene("SampleScene")
    
    if (name == "Text") then
        self:playText();
    elseif (name == "Depth") then
        self:playDepth();
    elseif (name == "Window") then
        self:playWindow();
    elseif (name == "Drag&Drop") then
        self:playDragDrop();
    elseif (name == "Popup") then
        self:playPopup();
    elseif name == "ProgressBar" then
        self:playProgress()
    elseif name == "Graph" then
        self:playGraph()
    elseif name == "Grid" then
        self:playGrid()
    elseif name == "Transition" then
        self:playTransition()
    end
end
