---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/5/8 14:19
---


require("LuaConf/RequireLuaFiles")
local ModalWaitingMain = class("ModalWaitingMain")

function awake()
    print("lua awake...")
    UIConfig.globalModalWaiting = "ui://ModalWaiting/GlobalModalWaiting";
    UIConfig.windowModalWaiting = "ui://ModalWaiting/WindowModalWaiting";
    ModalWaitingMain.New()
end

function ModalWaitingMain:Ctor()
    CS.UnityEngine.Application.targetFrameRate = 60
    Stage.inst.onKeyDown:Add(OnKeyDown)
    -- self.mainView = this:GetComponent(typeof(CS.FairyGUI.UIPanel)).ui
    self.mainView = UIPackage.CreateObject("ModalWaiting", "Main")  -- 这两行同 this:GetComponent(typeof(CS.FairyGUI.UIPanel)).ui
    GRoot.inst:AddChild(self.mainView)
    self.testView = require("Window4")
    self.mainView:GetChild("n0").onClick:Add(function() self.testView:Show() end)
    CS.UnityEngine.StartCoroutine(self:WaitSomeTime())
end

function ModalWaitingMain:WaitSomeTime()
    GRoot.inst:ShowModalWait()
    coroutine.yield(function() CS.UnityEngine:WaitForSeconds(3) end)
    GRoot.inst:CloseModalWait()
end

function ModalWaitingMain:OnKeyDown()
    if context.inputEvent.keyCode == CS.UnityEngine.KeyCode.Escape then
        CS.UnityEngine.Application.Quit();
    end
end


