---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/5/10 10:26
---

require("LuaConf/RequireLuaFiles")
local PullToRefreshMain = class("PullToRefreshMain")


function awake()
    print("lua awake...")
    UIConfig.globalModalWaiting = "ui://ModalWaiting/GlobalModalWaiting";
    UIConfig.windowModalWaiting = "ui://ModalWaiting/WindowModalWaiting";
    PullToRefreshMain.New()
end

function PullToRefreshMain:Ctor()
    CS.UnityEngine.Application.targetFrameRate = 60
    Stage.inst.onKeyDown:Add(OnKeyDown)
    CS.FairyGUI.UIObjectFactory.SetPackageItemExtension("ui://PullToRefresh/Header", typeof(CS.FairyGUI.ScrollPaneHeader))
    self:Init()
end

function PullToRefreshMain:Init()
    self.mainView = this:GetComponent(typeof(CS.FairyGUI.UIPanel)).ui;
    
    self.list1 = self.mainView:GetChild("list1").asList
    self.list1.itemRenderer = xutil.bind(self.RenderListItem1, self)
    self.list1:SetVirtual()
    self.list1.numItems = 1;
    self.list1.scrollPane.onPullDownRelease:Add(xutil.bind(self.OnPullDownToRefresh, self));
    
    self.list2 = self.mainView:GetChild("list2").asList
    self.list2.itemRenderer = xutil.bind(self.RenderListItem2, self)
    self.list2:SetVirtual()
    self.list2.numItems = 1
    self.list2.scrollPane.onPullUpRelease:Add(xutil.bind(self.OnPullUpToRefresh, self))
    
end

function PullToRefreshMain:RenderListItem1(index, obj)
    obj.title = "Item " .. (self.list1.numItems - index - 1)
end

function PullToRefreshMain:RenderListItem2(index, obj)
    obj.title = "Item " .. index
end

function PullToRefreshMain:OnPullDownToRefresh()
    local header = self.list1.scrollPane.header
    if header.ReadyToRefresh then
        header:SetRefreshStatus(2)
        self.list1.scrollPane:LockHeader(header.sourceHeight)
        CS.FairyGUI.Timers.inst:Add(2, 1, function(param) 
            self.list1.numItems = self.list1.numItems + 5
            header:SetRefreshStatus(3)
            self.list1.scrollPane:LockHeader(35)
            CS.FairyGUI.Timers.inst:Add(2, 1, function(param2)
                header:SetRefreshStatus(0)
                self.list1.scrollPane:LockHeader(0)
            end)
        end)
    end
end

function PullToRefreshMain:OnPullUpToRefresh()
    local footer = self.list2.scrollPane.footer
    footer:GetController("c1").selectedIndex = 1
    self.list2.scrollPane:LockFooter(footer.sourceHeight)

    CS.FairyGUI.Timers.inst:Add(2, 1, function(param)
        self.list2.numItems = self.list2.numItems + 5
        footer:GetController("c1").selectedIndex = 0
        self.list2.scrollPane:LockFooter(0)
    end)
   
end


function PullToRefreshMain:OnKeyDown()
    if context.inputEvent.keyCode == CS.UnityEngine.KeyCode.Escape then
        CS.UnityEngine.Application.Quit();
    end
end