---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/5/14 11:51
---

require("LuaConf/RequireLuaFiles")
local SpineMain = class("SpineMain")

function awake()
    print("lua awake...")
    SpineMain.New()
end

function SpineMain:Ctor()
    skeletonAnimation = this:GetComponent(typeof(CS.Spine.Unity.SkeletonAnimation))
    --skeletonAnimation.AnimationName = "Attack"
    aaa = 1
end

function update()
    if aaa==1 then
        skeletonAnimation.AnimationName = "Attack"
        aaa = 0
    end
    
end 