---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/5/10 11:47
---

require("LuaConf/RequireLuaFiles")
local TransitionMain = class("TransitionMain")

function awake()
    print("lua awake...")
    UIConfig.globalModalWaiting = "ui://ModalWaiting/GlobalModalWaiting";
    UIConfig.windowModalWaiting = "ui://ModalWaiting/WindowModalWaiting";
    TransitionMain.New()
end

function TransitionMain:Ctor()
    CS.UnityEngine.Application.targetFrameRate = 60
    Stage.inst.onKeyDown:Add(xutil.bind(self.OnKeyDown, self))
    self.endValue = 0
    self.startValue = 0
    self.mainView = this:GetComponent(typeof(CS.FairyGUI.UIPanel)).ui
    self.btnGroup = self.mainView:GetChild("g0").asGroup

    self.g1 = UIPackage.CreateObject("Transition", "BOSS").asCom;
    self.g2 = UIPackage.CreateObject("Transition", "BOSS_SKILL").asCom;
    self.g3 = UIPackage.CreateObject("Transition", "TRAP").asCom;

    self.g4 = UIPackage.CreateObject("Transition", "GoodHit").asCom;
    self.g5 = UIPackage.CreateObject("Transition", "PowerUp").asCom;
    self.g5:GetTransition("t0"):SetHook("play_num_now", xutil.bind(self.playNum, self));

    self.g6 = UIPackage.CreateObject("Transition", "PathDemo").asCom;

    self.mainView:GetChild("btn0").onClick:Add(function()
        self:play(self.g1)
    end)
    self.mainView:GetChild("btn1").onClick:Add(function() 
        self:play(self.g2)
    end)
    self.mainView:GetChild("btn2").onClick:Add(function() 
        self:play(self.g3)
    end)
    self.mainView:GetChild("btn3").onClick:Add(xutil.bind(self.play4, self));
    self.mainView:GetChild("btn4").onClick:Add(xutil.bind(self.play5, self));
    self.mainView:GetChild("btn5").onClick:Add(function() 
        self:play(self.g6)
    end)
end

function TransitionMain:play(target)
    self.btnGroup.visible = false
    GRoot.inst:AddChild(target)
    local t = target:GetTransition("t0")
    t:Play(function() 
        self.btnGroup.visible = true
        GRoot.inst:RemoveChild(target)
    end)
end

function TransitionMain:play4()
    self.btnGroup.visible = false
    self.g4.x = GRoot.inst.width - self.g4.width - 20
    self.g4.y = 100
    GRoot.inst:AddChild(self.g4)
    local t = self.g4:GetTransition("t0")
    t:Play(3, 0, function()
        self.btnGroup.visible = true
        GRoot.inst:RemoveChild(self.g4)
    end)
end

function TransitionMain:play5()
    self.btnGroup.visible = false
    self.g5.x = 20
    self.g5.y = GRoot.inst.height - self.g5.height - 100
    GRoot.inst:AddChild(self.g5)
    local t = self.g5:GetTransition("t0")
    self.startValue = 10000
    local add = math.random(1000, 3000)
    self.endValue = self.startValue + add
    self.g5:GetChild("value").text = "" .. self.startValue
    self.g5:GetChild("add_value").text = "" .. add
    t:Play(function()
        self.btnGroup.visible = true
        GRoot.inst:RemoveChild(self.g5)
    end)
end

function TransitionMain:playNum()
    CS.FairyGUI.GTween.To(self.startValue, self.endValue, 0.3):SetEase(CS.FairyGUI.EaseType.Linear):OnUpdate(function(tweener)
        self.g5:GetChild("value").text = "" .. math.floor(tweener.value.x)
    end);

end


function TransitionMain:OnKeyDown(context)
    if context.inputEvent.keyCode == CS.UnityEngine.KeyCode.Escape then
        CS.UnityEngine.Application.Quit();
    end
end