---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/4/27 19:01
---

local Windows = fgui.window_class()

function Windows:OnInit() end

function Windows:DoShowAnimation() end

function Windows:DoHideAnimation() end

function Windows:OnShown() end

function Windows:OnHide() end

function Windows:HideImmediately() end

function Windows:Show() end

return Windows