---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/5/8 14:52
---

local Window2 = fgui.window_class() --class("Window2", FairyGUI.LuaWindow)   
function Window2:Ctor() print_r(Window2 , " windows2 Ctor")  end

function Window2:OnInit()
    self.contentPane = fgui.UIPackage.CreateObject("ModalWaiting", "TestWin").asCom
    self.contentPane:GetChild("n1").onClick:Add(function()
        self:ShowModalWait();
        CS.FairyGUI.Timers.inst:Add(3, 1, function(param) self:CloseModalWait() end);
    end)
end

print_r(Window2 , " windows2 ")

return Window2